### ISSUE TITLE
Error after install w/ Radiant 0.9rc2 ActionMailer 2.3.7

### ISSUE THREAD

**Issue by mistergibson** [spanner/radiant-reader_group-extension#1]
I get this error after installation: (any advice on a workaround would be appreciated)

rake radiant:extensions:reader_group:migrate --trace

*\* Invoke radiant:extensions:reader_group:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
undefined method `radiant_layout' for ReaderNotifier:Class
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/actionmailer/lib/action_mailer/base.rb:400:in`method_missing'
/mnt/Storage/Shared/Development/Projects/groupware.orig/vendor/extensions/reader/app/models/reader_notifier.rb:3
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in `load_without_new_constant_marking'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in`load_file'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:379:in`load_file'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:259:in `require_or_load'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:425:in`load_missing_constant'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in `const_missing'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:92:in`const_missing'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:98:in `send'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:98:in`const_missing'
/mnt/Storage/Shared/Development/Projects/groupware.orig/vendor/extensions/reader_group/reader_group_extension.rb:38:in `activate'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/lib/radiant/extension.rb:86:in`activate'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/actionpack/lib/action_controller/routing/route.rb:205:in `to_proc'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/lib/radiant/extension_loader.rb:106:in`each'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/lib/radiant/extension_loader.rb:106:in `activate_extensions'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/lib/radiant/initializer.rb:196:in`after_initialize'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/railties/lib/initializer.rb:179:in `process'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/railties/lib/initializer.rb:113:in`send'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/railties/lib/initializer.rb:113:in `run'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/lib/radiant/initializer.rb:152:in`run'
/mnt/Storage/Shared/Development/Projects/groupware.orig/config/environment.rb:12
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/gems/1.8/gems/radiant-0.9.0.rc2/vendor/rails/railties/lib/tasks/misc.rake:4
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in`each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19

**Comment by mistergibson** [comment]
oops ... wrong venue - sorry
